on:
  push:
    branches:
      source

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    name: 'Deploy to GitHub Pages'
    steps:
    - name: check out
      uses: actions/checkout@v4
    - name: setup github
      run: |
        git config --global user.name 'Samson Wang'
        git config --global user.email 'wangzhilv@gmail.com'
        git fetch origin master
    - name: setup emacs
      uses: purcell/setup-emacs@v6.0
      with:
        version: 26.3
    - name: setup nikola
      run: |
        pip3 install --upgrade Nikola[extras]
        nikola --version
    - name: build and deploy
      run: nikola build && nikola github_deploy -m 'nikola auto deploy by gh action'
